### ISSUE TITLE
Huno rejected upload but uploads anyway

### ISSUE THREAD

**Issue by fIows** [z-ink/Uploadrr#5] opened 2024-06-22 09:21 UTC
Getting HUNO Rejected Upload after uploading but it still uploads fine.

**Comment by z-ink** [comment] 2024-06-22 17:05
The rejected upload happens due to a server code error when trying to determine if the upload was successful or not. I'll try to do a bit more testing on that, and have it go into an 'undetermined' pile and only use rejected when the response is clearly indicative of rejection (like in the even of name or info_hash already being in use), hopefully this avoids confusion.

Thanks for reporting!

**Comment by fIows** [comment] 2024-06-22 23:19
Okay thanks. Since it doesn't complete it's not going into my torrent client so I have to download the torrent manually not a big deal but just wanted you to know. Also not sure if I should make a new issue for this.
I have been having trouble with uploading just this file this is what I get.

```
Gathering info for The Ministry of Ungentlemanly Warfare.2024.2160p.UHD.BluRay.HDR10+.TrueHD 7.1.x265-SPHD.mkv
ID: The Ministry of Ungentlemanly Warfare.2024.2160p.UHD.BluRay.HDR10+.TrueHD 7.1.x265-SPHD.mkv
Exporting MediaInfo...
```
After that, it just exits. I tried using debug and still no errors it just quits.

**Comment by z-ink** [comment] 2024-06-24 16:40
@fIows does this only happen on HUNO? (the upload rejection)

As for the file, I assume path was wrapped in quotes? I opened a new issue, if you could add into that issue the command run in full, I'll try to reproduce thanks.

**Comment by fIows** [comment] 2024-06-25 03:36
I have only faced issues with HUNO so far

**Comment by z-ink** [comment] 2024-06-26 01:25
Should be fixed with a git pull 

 [Commit b0192ce](https://github.com/z-ink/Uploadrr/commit/b0192ce34f487c72248a6e397de626d8013dbab1)
 
 Issue seemed to be the writing of url to the torrent file, I may reinstate this once I can properly analyze the response from HUNO. (Just joined so end-of-month I should have upload privs)

**Closed by z-ink** 2024-06-26 01:25 UTC
